# Generated by Django 3.2.8 on 2021-10-26 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[(0, 'Secretario'), (1, 'Tesorero'), (2, 'Jefe')], max_length=2)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.persona')),
            ],
        ),
    ]
