# Generated by Django 3.2.8 on 2021-10-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('cedula', models.IntegerField()),
                ('uid', models.TextField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=20)),
                ('sangre', models.CharField(choices=[('O negativo', 'O negativo'), ('O positivo', 'O positivo'), ('A negativo', 'A negativo'), ('A positivo', 'A positivo'), ('B negativo', 'B negativo'), ('B positivo', 'B positivo'), ('AB negativo', 'AB negativo'), ('AB positivo', 'AB positivo')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('carrera', models.CharField(choices=[('Medicina', 'Medicina'), ('Enfermería', 'Enfermería'), ('Administración de Empresas', 'Administración de Empresas'), ('Contaduría Pública', 'Contaduría Pública'), ('Economía', 'Economía'), ('Derecho', 'Derecho'), ('Ingeniería Biomédica', 'Ingeniería Biomédica'), ('Ingeniería de Sistemas', 'Ingeniería de Sistemas'), ('Ingeniería Financiera', 'Ingeniería Financiera'), ('Ingeniería de Mercados', 'Ingeniería de Mercados'), ('Ingeniería en Energía', 'Ingeniería en Energía'), ('Ingeniería Mecatrónica', 'Ingeniería Mecatrónica'), ('Ingeniería Industrial', 'Ingeniería Industrial')], max_length=50)),
                ('semestre', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
